Feature/change searching of employer names on volunteer form to auto fill#595
CodeYourFuture/cyf-forms pull request #111
Opened 2023-01-14 00:38 UTC by youssef910

This is a:

- [x] ✨ **New feature** - new behaviour has been implemented
- [ ] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ✅ **Test backfill** - tests for existing behaviour were added but the behaviour itself hasn't changed
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

### Description
in Cyf forms when volunteer fills a for and selects "hear about code your future from employer "  a new field appears to select the  employer

- **Purpose** - 
to make the user able to type on the input and a list of suggestions will appear according to letters inserted

 In the local host, 
 1- checkout to the branch name
 2- filling the form and selecting the hear about code your future from employer 
 3- start typing the employer name
4- if the form is finished you can find the user created at the DB
5- when clicking on the wanted name it appears in the input box

### Links
story
https://github.com/orgs/CodeYourFuture/projects/18/views/2?pane=issue&itemId=9700853

- [ ] I have written a title that reflects the relevant ticket
- [x] I have written a description that says what the PR does and how to validate it
- [x] I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [ ] I have added a link to this PR to the ticket
- [ ] I have made the PR to `staging` from a branch named `<category>/<name>`, e.g. `feature/edit-spaceships` or `bugfix/restore-oxygen`
- [ ] I have completed the manual tests [described here](https://github.com/CodeYourFuture/tech-team/wiki/Manual-Test-Procedures)
- [ ] I have requested reviewers here and in my team chat channel

- [ ] I have spoken with my PM or TL about any parts of this task that may have become out-of-scope, or any additional improvements that I now realise may benefit my project
- [ ] I have added tests, or new tests were not required
- [ ] I have updated any documentation (e.g. diagrams, schemas), or documentation updates were not required

- [ ] I have updated the Swagger API documentation in `src/swagger/routes/`
- [ ] I have explicitly tested the access rights for _at least_ unauthenticated, admin and non-admin cases

2023-01-14 10:53 UTC, textbook requested changes
This is neat! A few things to think about:

1. I think an acceptance criterion has been missed: _"we should show **first** all employers starting with that letter"_. If I use e.g. `t`, the employers starting with it don't even make the top 10. (It's probably one for a later iteration, but some sort of [string metric](https://en.wikipedia.org/wiki/String_metric) might be an interesting thing to research.) 
2. This implementation isn't accessible, the autofill options aren't reachable from the keyboard.
3. This is a relatively complex component with a number of interactions, it would be really nice to see some lower level tests so it's covered by more than just a single part of an E2E test.

2023-01-14 10:53 UTC, textbook commented on e2e/integration/journey.test.js
> +  })
You should still be able to do this with Testing Library selectors, e.g.:
```suggestion
  cy.findByRole('option', { name: /capgemini/i }).click()
```

2023-01-14 10:53 UTC, textbook commented on src/Components/forms/index.js
> +    this.setState({ employer, errors, submitted: false, formInComplete: false })
You don't need to interpolate a string into a template string, just use the string:
```suggestion
    errors['Employer'] = false
    this.setState({ employer, errors, submitted: false, formInComplete: false })
```
and then hopefully it's more obvious that this is equivalent to:
```suggestion
    errors.Employer = false
    this.setState({ employer, errors, submitted: false, formInComplete: false })
```
In general you shouldn't mutate state held by React, but it looks like the other handlers do this too and enough is changing that it triggers a re-render, so maybe that's OK.

2023-01-14 10:53 UTC, textbook commented on src/Components/forms/inputs/AutoFillDropDown.js
> +export default ({ employerOnChange, isEmpty, label, name, arrayList }) => {
Components should generally have _names_ (it looks like a lot of the others don't either, but it means your React Dev Tools is full of "Anonymous" entries). Either:
```suggestion
export default function AutoFillDropDown({ employerOnChange, isEmpty, label, name, arrayList }) {
```
or:
```suggestion
const AutoFillDropDown = ({ employerOnChange, isEmpty, label, name, arrayList }) => {
```
then `export default AutoFillDropDown`.

2023-01-14 20:41 UTC, youssef910 commented on e2e/integration/journey.test.js
> +  })
applied the required changes

2023-01-14 20:41 UTC, youssef910 commented on src/Components/forms/index.js
> +    this.setState({ employer, errors, submitted: false, formInComplete: false })
applied the required changes

2023-01-14 20:41 UTC, youssef910 commented on src/Components/forms/inputs/AutoFillDropDown.js
> +export default ({ employerOnChange, isEmpty, label, name, arrayList }) => {
applied the required changes

2023-01-14 21:12 UTC, youssef910 commented
> This is neat! A few things to think about:
> 
> 1. I think an acceptance criterion has been missed: _"we should show **first** all employers starting with that letter"_. If I use e.g. `t`, the employers starting with it don't even make the top 10. (It's probably one for a later iteration, but some sort of [string metric](https://en.wikipedia.org/wiki/String_metric) might be an interesting thing to research.)
> 2. This implementation isn't accessible, the autofill options aren't reachable from the keyboard.
> 3. This is a relatively complex component with a number of interactions, it would be really nice to see some lower level tests so it's covered by more than just a single part of an E2E test.

the first 2 points covered but the third point is hard for me now to do it

2023-01-14 21:34 UTC, textbook commented
- I think the current implementation works for a single letter (first anything _starting_ with that letter, than anything else _containing_ that letter) but **not** for multiple letters (anything _starting_ with that prefix). So for example if I type "ca" I see Capgemini and Carnall Farrar (as I would expect) but **not** e.g. Digital Cabinet Office or Apolitical (as I would also expect) and also **not**  e.g. MadeTech or BMChealth (which I wouldn't have expected but which I think the story is asking for). It's slightly trickier because the example in the story doesn't seem to match [the current employer list](https://github.com/CodeYourFuture/cyf-forms/blob/f65297a63082d3d2a093d9fb9a7c614d41a63390/src/Components/forms/data.json#L50-L115).

- The options are now accessible by tabbing, thank you - it's not interactable in quite the way I'd imagined, but this isn't my area of expertise, it's more a question to PM and design how it should work (👋 @Domenico-cyf @kfklein15).

- A basic test for this component (after you `yarn add -D @testing-library/{jest-dom,react,user-event}`) would look much like what you do at the Cypress level:

    ```javascript
    import '@testing-library/jest-dom'
    import { render, screen, waitFor } from '@testing-library/react'
    import userEvent from '@testing-library/user-event'
    
    import AutoFillDropDown from './AutoFillDropDown'
    
    describe('AutoFillDropDown', () => {
      it('shows a matching option', async () => {
        const user = userEvent.setup()
        render(
          <AutoFillDropDown
            arrayList={[{ name: 'Capgemini' }]}
            employerOnChange={() => {}}
            isEmpty={false}
            label="Employer"
            name="employer"
          />
        )
    
        await user.type(screen.getByRole('textbox', { name: /employer/i }), 'cap')
    
        expect(
          screen.getByRole('option', { name: /capgemini/i })
        ).toBeInTheDocument()
      })
    })
    ```
    This is useful because it allows a much more rapid feedback cycle with a more controllable list of employers (and also tells you `Warning: Each child in a list should have a unique "key" prop.`!)

2023-01-14 21:42 UTC, youssef910 commented
```
> Acceptance criteria
> 
> The selection functionality of Employer should use auto-filling
> [Figma for auto-fill](https://www.figma.com/proto/mtLoYXLt5BWUWHlb1B4HAJ/Employer-auto-fill?node-id=2%3A15&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2%3A15)
> **When typing a letter (for example A), we should show first all employers starting with that letter (for example Adyen, And Digital, Apolitical, Arnold Clark, Avanade) AND that have the letter in the name (7digital, B4B Payments, for example)**
> When typing two letters (for example Ar), we should show only employers that start with those letters (for example Arnold Clark) AND that have the letter in the name (Alfa Financial Software, for example)
> Names should always show in alphabetical order
> 
```

I tried to follow the acceptance criteria as much as I understood it  it asked to show when only one letter it should how employers starts with the letter  then the employers who have the letter included in the name

2023-01-14 21:56 UTC, textbook commented
Yes, it works for one letter. It's the other cases it doesn't work for. This is why I'm suggesting testing; you can easily create cases, validate with the product folk that they're correct, then implement against that. For example:
```js
  it('finds characters within words', async () => {
    const user = userEvent.setup()
    render(
      <AutoFillDropDown
        arrayList={['Arnold Clark', 'Alfa Financial Software', 'BMChealth'].map(
          name => ({ _id: name, name })
        )}
        employerOnChange={() => {}}
        isEmpty={false}
        name="employer"
        label="Employer"
      />
    )

    await user.type(screen.getByRole('textbox', { name: /employer/i }), 'ar')

    expect(screen.getByRole('option', { name: /arnold/i })).toBeInTheDocument()
    expect(screen.getByRole('option', { name: /alfa/i })).toBeInTheDocument()
    expect(
      screen.queryByRole('option', { name: /bmc/i })
    ).not.toBeInTheDocument()
  })
```

2023-01-16 19:58 UTC, textbook requested changes

2023-01-16 19:58 UTC, textbook commented on src/Components/forms/data.json
> +    { "name": "Alfa Financial Software", "_id": "Alfa Financial Software" },
I don't think adding new employers to the site is part of this ticket. Last update was separate: CodeYourFuture/tech-team#593

2023-01-16 19:58 UTC, textbook commented on src/Components/forms/inputs/AutoFillDropDown.test.js
> +import '@testing-library/jest-dom' // this should go in ./src/setupTests.js
Note the comment 😅

2023-01-16 19:58 UTC, textbook commented on src/Components/forms/inputs/AutoFillDropDown.test.js
> +import exampleData from '../data.json'
The great thing about writing low-level tests is that you don't need to use the real data. You can use simpler (or more complex, if needed) examples that recreate the functionality required. So you don't have to change the employers actually shown on the site to test against the example provided in the story.

2023-01-16 19:58 UTC, textbook commented on src/Components/forms/inputs/AutoFillDropDown.test.js
> +  it('finds characters within words', async () => {
The nesting here seems wrong:
```js
describe('...', () => {  // (1) ok
  describe('...', () => {  // (2) not necessarily wrong, you can nest these, but did you mean to?
    it('...', () => {  // fine, test inside (2)
    })
    expect(...)  // this isn't inside a test
  })
  it('...', () => {  // test inside (1)
```
Could you add the tests to the pipeline (see `.circleci/config.yml`) so that they run as part of the PR checks?

2023-01-16 19:58 UTC, textbook commented on src/Components/forms/inputs/AutoFillDropDown.js
> +import React, { useState } from 'react'
There's something slightly awkward happening in this file. We're passing in `name="employer"` and `label="Who is your employer? *"` when we render the `AutoFillDropDown`, which implies that it's a generic component like the others. But we also repeatedly refer to "employer(s)" in the code within this file. It's too early to know how much of this is reusable; I'd advocate for making it explicitly an `EmployerDropDown`, then we can refactor if and when we have multiple such controls and know what's common.

2023-01-16 20:09 UTC, youssef910 commented on src/Components/forms/data.json
> +    { "name": "Alfa Financial Software", "_id": "Alfa Financial Software" },
i just wanted to have matching between the test and what is shown on the screen and the table in the ticket , can be returned to the original values it is okay
and i think this list will be replaced by API in  a future ticket

2023-01-16 20:09 UTC, youssef910 commented on src/Components/forms/inputs/AutoFillDropDown.test.js
> +import exampleData from '../data.json'
:)

2023-01-16 20:42 UTC, youssef910 commented on src/Components/forms/inputs/AutoFillDropDown.test.js
> +import '@testing-library/jest-dom' // this should go in ./src/setupTests.js
removed

2023-01-16 20:53 UTC, youssef910 commented on src/Components/forms/inputs/AutoFillDropDown.test.js
> +  it('finds characters within words', async () => {
removed the extra nesting

2023-01-16 20:53 UTC, youssef910 commented on src/Components/forms/inputs/AutoFillDropDown.js
> +import React, { useState } from 'react'
changed the name of the component

2023-01-16 21:06 UTC, youssef910 commented on src/Components/forms/data.json
> +    { "name": "Alfa Financial Software", "_id": "Alfa Financial Software" },
reverted the changes

2023-01-16 21:44 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +  ).not.toBeInTheDocument()
This expectation is still not inside a test. I guess it's not failing because there's nothing on the screen, but expectations should _only_ be inside the callback to `it`.

2023-01-16 21:44 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +        arrayList={employerList}
You don't necessarily need to use the same employer list in every test - it's usually easier to craft a specific input for each case you're trying to demonstrate.

2023-01-16 21:44 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +describe('EmployerDropDown', () => {
We have tests here for the case of two- and three-letter inputs, but the acceptance criteria mentioned another kind that might be relevant to cover. Also I'd be inclined to test the next part - what happens when the user types a bit, then clicks on one of the inputs (I know we also test this at the E2E level, but it's good to practice working with these tests).

2023-01-17 20:36 UTC, kfklein15 commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +describe('EmployerDropDown', () => {
@textbook , I agree it is good practice, and I cannot believe I am suggesting less automated testing!, but could we avoid the user types scenario and keep it only with the e2e scenario? We are asking for many changes, so I am trying to ensure we prioritise the must-haves. 

Which one is the other scenario the AC is mentioning? The alphabetical order?

2023-01-17 20:56 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +  ).not.toBeInTheDocument()
moved it inside

2023-01-17 21:47 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +  ).not.toBeInTheDocument()
👍 but I don't think you've pushed that commit

2023-01-17 21:49 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +  ).not.toBeInTheDocument()
Just still working the file will do all changes and push all changes together

2023-01-17 21:49 UTC, textbook commented on src/Components/forms/inputs/AutoFillDropDown.test.js
> +import '@testing-library/jest-dom' // this should go in ./src/setupTests.js
No, I mean _read_ the comment!

2023-01-17 21:50 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +  ).not.toBeInTheDocument()
Ah OK. Please comment when you've pushed the relevant changes, otherwise I get a notification then get confused when I can't see them!

2023-01-17 21:56 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +describe('EmployerDropDown', () => {
> could we avoid the user types scenario and keep it only with the e2e scenario?

Yes, of course; I only said that I'd be inclined to do it. We've had a few complications around this functionality, and tests at this level gives the developer much faster and finer-grained feedback to get confident that the component's behaving as intended. (It also gives the opportunity to try something _slightly_ different to the tests so far, which helps embed learning and understanding.)

> Which one is the other scenario the AC is mentioning? The alphabetical order?

No, my understanding from the comments on the story was that the alphabetical order was being split out. Youssef do you know which part isn't currently covered?

2023-01-23 14:09 UTC, kfklein15 commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +describe('EmployerDropDown', () => {
@textbook, the comments are from 3 months ago. The AC has been reviewed as a team in the last planning, so should be up-to-date.

@youssef910 , can you confirm?

2023-01-23 14:15 UTC, kfklein15 commented
> * I think the current implementation works for a single letter (first anything _starting_ with that letter, than anything else _containing_ that letter) but **not** for multiple letters (anything _starting_ with that prefix). So for example if I type "ca" I see Capgemini and Carnall Farrar (as I would expect) but **not** e.g. Digital Cabinet Office or Apolitical (as I would also expect) and also **not**  e.g. MadeTech or BMChealth (which I wouldn't have expected but which I think the story is asking for). It's slightly trickier because the example in the story doesn't seem to match [the current employer list](https://github.com/CodeYourFuture/cyf-forms/blob/f65297a63082d3d2a093d9fb9a7c614d41a63390/src/Components/forms/data.json#L50-L115).
> * The options are now accessible by tabbing, thank you - it's not interactable in quite the way I'd imagined, but this isn't my area of expertise, it's more a question to PM and design how it should work (👋 @Domenico-cyf @kfklein15).
> * A basic test for this component (after you `yarn add -D @testing-library/{jest-dom,react,user-event}`) would look much like what you do at the Cypress level:
>   ```js
>   import '@testing-library/jest-dom'  // this should go in ./src/setupTests.js
>   import { render, screen, waitFor } from '@testing-library/react'
>   import userEvent from '@testing-library/user-event'
>   
>   import AutoFillDropDown from './AutoFillDropDown'
>   
>   describe('AutoFillDropDown', () => {
>     it('shows a matching option', async () => {
>       const user = userEvent.setup()
>       render(
>         <AutoFillDropDown
>           arrayList={[{ _id: 'Capgemini', name: 'Capgemini' }]}
>           employerOnChange={() => {}}
>           isEmpty={false}
>           label="Employer"
>           name="employer"
>         />
>       )
>   
>       await user.type(screen.getByRole('textbox', { name: /employer/i }), 'cap')
>   
>       expect(
>         screen.getByRole('option', { name: /capgemini/i })
>       ).toBeInTheDocument()
>     })
>   })
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   This is useful because it allows a much more rapid feedback cycle with a more controllable list of employers. I've written some tutorials that might help, see e.g. https://blog.jonrshar.pe/2020/Nov/22/js-tdd-e2e.html.

@youssef910 , can you show me how the accessibility piece is working? so that I can confirm if I am happy with it.
FYI @esma-g

2023-01-23 16:58 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +describe('EmployerDropDown', () => {
the current behavior that when the user start typing the results appears are:
1- the names with the letter or letters typed in the beginning of the name
2- the names with the letter or letters typed in any part of the name
and as the letters increases the choices is filtered till it find name or the intered value is added to the input box if it is not included.( but in this scenario there is error appears as there is no input and the box is empty) I left it as this because in some comments there was concerns  about inserting new names to the DB so I think we can leave it blocked for now tell we find  proper solution 
I hope I am understanding the question in the right way

2023-01-24 11:10 UTC, kfklein15 commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +describe('EmployerDropDown', () => {
Yes, so the behaviour is accurate. Let's try to keep the test as slick as possible, so we only spend part of the 2 weeks on it. 
Can you @youssef910, and whoever is helping you just describe which test will be built and covered? We can then add other stories later to build more on the next sprint.

2023-02-01 18:47 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +        arrayList={employerList}
done each test has its set of data

2023-02-01 18:48 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +describe('EmployerDropDown', () => {
i fixed the tests and added as much cases as I can do

2023-02-02 11:00 UTC, kfklein15 commented
Thanks. Make sure you ask for the team to review it so we can move forward.

2023-02-02 16:05 UTC, SaadiaELF commented
@youssef910 , I would suggest to create  a test folder to hold the tests. Since there are no tests yet, It will be good to create it now :) 
Also I found this recurrent warning on the tests
```js
console.error
    Warning: An update to EmployerDropDown inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at EmployerDropDown (/Users/cyf-elfekak/Desktop/CYF_Products/cyf-forms/src/Components/forms/inputs/EmployerDropDown.js:5:29)
```
Maybe this documentation can help you [Fix the "not wrapped in act(...)" warning](https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning)
The code works perfectly , well done 👏

2023-02-02 18:01 UTC, textbook reviewed
This is a huge step forward, well done! The third-party component is much more accessible for less maintainance work on our part, I think that's a good choice.

Two hopefully minor things to address in the comments:

- Clarify the sorting of the results (primarily a _product_ decision)
- Could the new component be a drop-in replacement for the old one, rather than requiring changes in the root form too?

The rest are for you to think about but not blocking anything.

Also FYI @SaadiaELF I actually think it's better to have the tests be siblings of the things they're testing like this, rather than a separate `__tests__` directory (where you end up with things like `import ThingToTest from "../../../back/down/again/ThingToTest"`, instead of just `import ThingToTest from "./ThingToTest"`). It's certainly the convention in React apps. But I certainly agree that we shouldn't have pages of `not wrapped in act(...)` - I just helped a team I was engaged with remove ~14,000 lines of output from their tests, which made them run much faster _and_ meant they could actually see when something actually relevant showed up.

2023-02-02 18:47 UTC, kfklein15 commented on e2e/integration/journey.test.js
> +  cy.get('input[id="employer"]').type('Ca').type('{enter}')
Answering: "Clarify the sorting of the results (primarily a product decision)" - alphabetical order should be used to sort the names of the employers.

2023-02-02 21:09 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.js
> +  }
in relation to "Other" i managed to make the sorting function add it to the end of the results.
also as relation to this I have a question to cla
![Screenshot from 2023-02-02 20-55-45](https://user-images.githubusercontent.com/47015754/216448270-f14631d8-23ee-4420-a430-b5d2faea8457.png)
rify @kfklein15  in case the  input is not included in the employers "as we will not activate the option of adding a new employer now as it has a separate task" so the default of react-select says no Options  but I can change it to another message is "'employer not Found? Please Select Other'" will be a good message? any way this Option of Other shouldn't be available after adding the ability to add new employer

2023-02-02 21:11 UTC, youssef910 commented on src/Components/forms/inputs/index.js
> +            employerOnChange={employerOnChange}
in react-select getting the value inserted is managed by e.value  but on the original onChange function which used in the other dropdown it debends on event.target.value that's why I created employerOnchange

2023-02-02 21:49 UTC, youssef910 commented on src/Components/forms/data.json
> +    { "name": "Avaloq", "_id": "Avaloq" },
when i added the new employers i forgot which one was already her and which one is added

2023-02-02 21:55 UTC, textbook commented on src/Components/forms/inputs/index.js
> +            employerOnChange={employerOnChange}
That's helpful context, thank you. It's really important in software development to try to limit the scope of changes, _especially_ when they're due to an external (`react-select`'s, in this case) design decision. Rather than drill a whole new function through two layers, why not use `EmployerDropDown` to adapt the component we're wrapping to _our_ API? In this case that could look like e.g.:

```jsx
onChange={e => onChange({ target: { name: "employer", type: "text", value: e.value } })}
```

Note that this is crucial to how this component is used by the rest of the application, but _not_ covered by the current tests (which just use an empty function for `employerOnChange`, rather than e.g. a `jest.fn()` whose interactions could be [asserted on](https://jestjs.io/docs/mock-functions)).

2023-02-02 22:08 UTC, textbook commented on e2e/integration/journey.test.js
> +  cy.get('input[id="employer"]').type('Ca').type('{enter}')
Ah if only it were that simple! They're mostly alphabetical, but we already have the fact that Other appears at the end of the list (and now I think about maybe should _always_ be shown, irrespective of the text so far?) The user story asks that a prefix match be moved to the _top_ of the list:

> we should show first all employers starting with that letter

I'm not really sure why the one- and two-letter cases are called out separately when they seem to be fundamentally the same, though. The _current_ implementation in this PR orders matches by how close the search text is to the start of the string, but I don't think that's quite what's being asked for. I think what's wanted is:

1. Companies _starting with_ the search text, in alphabetical order
2. Companies _including but **not** starting with_ the search text, in alphabetical order
3. "Other"

An easier first iteration might be that we just _filter_ the existing list, so you'd get 2. and 3. above, then implement 1. later.

2023-02-02 22:35 UTC, youssef910 commented on e2e/integration/journey.test.js
> +  cy.get('input[id="employer"]').type('Ca').type('{enter}')
is this the sort that you are suggesting?
![Screenshot from 2023-02-02 22-34-24](https://user-images.githubusercontent.com/47015754/216464865-b378af23-4380-4329-ae6c-996ac8412f96.png)
![Screenshot from 2023-02-02 22-34-13](https://user-images.githubusercontent.com/47015754/216464870-990c37cd-6f25-4054-a264-107ce583c4f8.png)

2023-02-02 23:39 UTC, textbook commented on e2e/integration/journey.test.js
> +  cy.get('input[id="employer"]').type('Ca').type('{enter}')
On the second one I'd expect:

- Remote.com
- Scottish Power
- Yoti
- Other

None _start with_ `ot`, so should just be in alphabetical order. I [had a play](https://github.com/CodeYourFuture/cyf-forms/compare/feature/595-employer-autofill?expand=1) with what `react-select` does straight out of the box and it gives us 2. and 3. immediately, I wonder if that's sufficient for now?

2023-02-03 09:21 UTC, kfklein15 commented
> * The options are now accessible by tabbing, thank you - it's not interactable in quite the way I'd imagined, but this isn't my area of expertise, it's more a question to PM and design how it should work (👋 @Domenico-cyf @kfklein15).

Jon, what did you mean by this? Maybe I missed something when I checked it. Thanks!

2023-02-03 09:24 UTC, kfklein15 commented on e2e/integration/journey.test.js
> +  cy.get('input[id="employer"]').type('Ca').type('{enter}')
Yes, it is sufficient for now, @textbook and @youssef910 
We can then iterate on it if needed.

2023-02-03 09:25 UTC, kfklein15 commented on src/Components/forms/inputs/EmployerDropDown.js
> +  }
Good phrase, just not a fan of capitals in the middle and not in the beginning. So let's use: Employer not found? Please select "Other".

2023-02-03 16:39 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.js
> +  }
added Employer not found? Please select "Other". message

2023-02-03 16:39 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +import '@testing-library/jest-dom'
moved it to ./src/setupTests.js

2023-02-03 16:40 UTC, youssef910 commented on src/Components/forms/inputs/index.js
> +            employerOnChange={employerOnChange}
Thanks for the help 
i changed it and used the original  onOhange which used on other components

2023-02-03 16:41 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +  it('finds characters within words', async () => {
i was already thinking about that but when the test passed I forgot to change it :D
it is changed to foreach

2023-02-03 16:42 UTC, youssef910 commented on e2e/integration/journey.test.js
> +  cy.get('input[id="employer"]').type('Ca').type('{enter}')
i am keeping it as it is on the screen shot with other at the end  when I tried to sort it alphabetically it is not working as expected we can change it later if needed

2023-02-03 16:44 UTC, youssef910 commented
> @youssef910 , I would suggest to create a test folder to hold the tests. Since there are no tests yet, It will be good to create it now :) Also I found this recurrent warning on the tests
> 
> ```js
> console.error
>     Warning: An update to EmployerDropDown inside a test was not wrapped in act(...).
>     
>     When testing, code that causes React state updates should be wrapped into act(...):
>     
>     act(() => {
>       /* fire events that update state */
>     });
>     /* assert on the output */
>     
>     This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
>         at EmployerDropDown (/Users/cyf-elfekak/Desktop/CYF_Products/cyf-forms/src/Components/forms/inputs/EmployerDropDown.js:5:29)
> ```
> 
> Maybe this documentation can help you [Fix the "not wrapped in act(...)" warning](https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning) The code works perfectly , well done clap

I didn't manage to fix this issue tried to follow the documentation but it always break the test "which I hardly made if pass " 
i hope this error don't affect the behavior of the code

2023-02-04 09:05 UTC, textbook commented on src/Components/forms/index.css
> +
Does this actually do anything? I realised your branch looked the same as mine and suspect this is leftover from pre-React Select iterations. It's kind of hard to see what exactly gets rendered (as it disappears when you try to interact with the element inspector), but doing:

```js
it('does stuff', async () => {
    const user = userEvent.setup()
    render(
      <EmployerDropDown
        arrayList={[
          { name: 'Beamery', _id: 'Beamery' },
          { name: 'American Express ', _id: 'American Express ' },
          { name: 'Capgemini', _id: 'Capgemini' },
          { name: 'Capital', _id: 'Capital' }
        ]}
        onChange={() => {}}
        isEmpty={false}
      />,
      { hidden: true }
    )
    await user.click(screen.getByRole('combobox', { id: 'employer' }))
    screen.debug()
  })
```

let me see that the list part looks like:

```html
            <div
              class=" css-1nmdiq5-menu"
              id="react-select-4-listbox"
            >
              <div
                class=" css-1n6sfyn-MenuList"
              >
                <div
                  aria-disabled="false"
                  class=" css-d7l1ni-option"
                  id="react-select-4-option-0"
                  tabindex="-1"
                >
                  Beamery
                </div>
```
so these classes don't match anything.

2023-02-04 09:05 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.js
> +const EmployerDropDown = ({ onChange, isEmpty, arrayList, name }) => {
`name` is unused (and isn't passed by the parent any more).

2023-02-04 09:06 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.js
> +    }))
The `item` has _two_ properties, `name` and `_id`. Yes, for all the values we have they're the same (and yet it seems nobody thought to `map` over a list of strings 🤷), but is that accidental or essential duplication? I would guess the point of that was that we wouldn't _necessarily_ have to have the visible name be the same as the stored ID, but here you ignore the latter entirely. If someone later adds an employer where the name and ID _do_ differ, which the array in `data.json` has an affordance for, this component will send the wrong value to the API. I think it should be:

```suggestion
    .map(item => ({
      value: item._id,
      label: item.name
    }))
```
or use [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#syntax):
```suggestion
    .map(({ _id, name }) => ({ value: _id, label: name }))
```

2023-02-04 09:06 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.js
> +      <Label htmlFor="employer">"Who is your employer? *"</Label>
There are _"literal quotes"_ in the label:

<img width="506" alt="Screenshot 2023-02-03 at 22 53 01" src="https://user-images.githubusercontent.com/785939/216729182-bfe02b4c-28de-4b65-868e-5167c8c9cf58.png">

2023-02-04 09:06 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.js
> +        className={`form-control ${isEmpty && 'is-empty'}`}
Putting it in a `form-control` adds extra borders, which looks a bit weird (see previous screenshot).

Also note `isEmpty && 'is-empty'` can evaluate to either `false`, `undefined` or `'is-empty'`, _all of which_ will appear as classes on the element (false-y values aren't skipped by [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)):
```html
<div class="form-control undefined css-b62m3t-container">
  <!-- ... -->
</div>
```
This doesn't really _do_ anything, as we don't have any classes named `false` or `undefined` (thankfully!) but it's important to be clear on what the code actually does.

2023-02-04 09:06 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.js
> +        onInputChange={inputVal => setValue(inputVal)}
It seems to be this that's causing all of the warnings in the tests. It's a big problem because we have about 15 lines of useful output and about 1,500 (!!) of warnings and tracebacks. The point of unit tests is that they run fast and give useful feedback to developers, neither of which can be the case when only 1% of the output is valuable. This isn't happening on [my branch](https://github.com/CodeYourFuture/cyf-forms/compare/feature/595-employer-autofill), I tried a few things and it seems to be a difference in dependencies - try running `yarn upgrade` to get the latest versions compatible with the ranges in our package file (you should get changes _only_ in `yarn.lock`).

2023-02-04 09:06 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.js
> +        }
How did this feel, by comparison to the previous implementation? Do you see what I mean about using our component to adapt the third-party component to fit neatly into our app, rather than the other way around? This is a helpful principle to have in mind in general, as it protects (most of) our code from any future changes to our dependencies' APIs.

2023-02-04 09:06 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +    const notAppearingApplicants = [
```suggestion
    const notAppearingEmployers = [
```

2023-02-06 22:48 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.js
> +        }
this was really helpful and this keeps building in the logic and ways to think when I am trying to do things like this.

2023-02-07 00:16 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.js
> +        onInputChange={inputVal => setValue(inputVal)}
after doing yarn upgrade all the warnings disappeared, should I push the changes in yarn.lock?
and if you allowed me I used  your test cases in your branch and added to them some of my test cases after learning from your way.

2023-02-07 00:18 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.js
> +      : 0
as it is not required any more to sort  Employers in this way I will remove the sorting function and remove the value use state as it is not needed any more.

2023-02-07 00:28 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.js
> +const EmployerDropDown = ({ onChange, isEmpty, arrayList, name }) => {
removed it

2023-02-07 00:29 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.js
> +    }))
changed it to use _id  and name values

2023-02-07 00:30 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.js
> +      <Label htmlFor="employer">"Who is your employer? *"</Label>
removed the "literal quotes" copy mistake

2023-02-07 00:33 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.js
> +        className={`form-control ${isEmpty && 'is-empty'}`}
used is-empty as class name  i just wanted to use the used in other validation as in other components but  but I did  wrong

2023-02-07 00:33 UTC, youssef910 commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +    const notAppearingApplicants = [
removed it just kept the appearing results only

2023-02-07 00:37 UTC, youssef910 commented on src/Components/forms/index.css
> +
i was confused to and don't know how to match the wanted results . thanks to the help from your branch taught me a lot and will back for it again when I have time to understand testing in a better way

2023-02-07 18:23 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.test.js
> +    const notAppearingApplicants = [
The problem with only checking what's shown is that there's nothing that makes sure the other things _aren't_ shown - if the filtering stopped working and the user was still being shown the whole list, the test would still pass. One way to approach this with less repetition is to get an array of what options are shown and assert it's as expected, see https://github.com/CodeYourFuture/cyf-forms/commit/c0bb04309d7f20cad6783e7652207230ff95d704#diff-e88a6f665f738ebe61b0e22f222574d559c18437e990f903f42155c362c46a46

2023-02-07 18:24 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.js
> +        onInputChange={inputVal => setValue(inputVal)}
Yes, the changes to the lockfile are what ensures we don't get a different set of dependencies and a bunch of warnings in CI or on someone else's machine. And of course, you're welcome to take any of the code from that branch.

2023-02-07 18:26 UTC, textbook commented on src/Components/forms/inputs/EmployerDropDown.js
> +        className={`form-control ${isEmpty && 'is-empty'}`}
It's not really your fault, sadly most of the others have the same problem!

2023-02-07 18:31 UTC, textbook approved these changes
This works as expected, with the [approved change](https://github.com/CodeYourFuture/cyf-forms/pull/111#discussion_r1095551618) to de-scope sorting the filtered employer names. It's also accessible (can be used from the keyboard) and tested at the unit and E2E levels. It looks slightly different from the other controls, but given its _behaviour_ is also different I don't think that's a big problem. Awesome job, thank you so much for persevering!

2023-02-07 22:50 UTC, merged

2023-02-08 16:14 UTC, AliNurisiahsiahi commented
[worked](https://www.loom.com/share/1cfb47ebd8864153acb88344d7d8bc0b) on QA.

2023-02-09 10:05 UTC, AliNurisiahsiahi commented
> could you track your testing as [reviews](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews) (ideally approving or requesting changes, rather than just commenting) on the relevant PRs please, rather than comments on a [merged PR](https://github.com/CodeYourFuture/cyf-forms/pull/111#issuecomment-1422876996) or [story](https://github.com/CodeYourFuture/tech-team/issues/595#issuecomment-1422833469) - you're reviewing this _in QA_, for example, so if you're saying it works you should be approving a PR _from feature branch to staging_ (likewise if you were reviewing it _in staging_, you'd be approving a PR _from staging to production_). If there isn't a PR open, just create one (e.g. via `https://github.com/CodeYourFuture/<repo>/compare`) and ask the relevant author to fill in the details.

Thank you :pray::skin-tone-2: