Add I-am-not-sure option only the UI after the teams data is received
CodeYourFuture/cyf-forms pull request #139
Opened 2023-09-15 15:26 UTC by khmdagal

This is a:

- [ ] ✨ **New feature** - new behaviour has been implemented
- [ ] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ✅ **Test backfill** - tests for existing behaviour were added but the behaviour itself hasn't changed
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

### Description

- **Purpose** - 
To allow new volunteers to choose the "I am not sure" option when choosing which team they want to join if they are not sure.

- This ticket is a spin-off of [692](https://github.com/CodeYourFuture/tech-team/issues/692)

- **How it works and to check** - 
- When a volunteer should see the "I am not sure" option in the drop-down menu.
- "I am not sure" option should be the last or the bottom option.
- On the dashboard, it should show "Select team", If a new volunteer chooses the "I am not sure" option on the form.
- Validation of this already included  [692](https://github.com/CodeYourFuture/tech-team/issues/692)

### Links

Ticket:  https://github.com/CodeYourFuture/tech-team/issues/765 

### Author checklist

- [ ] I have written a title that reflects the relevant ticket
- [ ] I have written a description that says what the PR does and how to validate it
- [ ] I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [ ] I have added a link to this PR to the ticket
- [ ] I have made the **Draft PR** to `qa` from a branch named **`feature-765-add-iam-not-sure-option-to-the-volunteer-teams-question`**
- [ ] I have completed the manual tests [described here](https://github.com/CodeYourFuture/tech-team/wiki/3.-How-we-work#manual-test-procedures)
- [ ] I have requested reviewers here and in my team chat channel

- [ ] I have spoken with my PM or TL about any parts of this task that may have become out-of-scope, or any additional improvements that I now realise may benefit my project
- [ ] I have added tests, or new tests were not required
- [ ] I have updated any documentation (e.g. diagrams, schemas), or documentation updates were not required

2023-09-18 12:46 UTC, SaadiaELF requested changes
Looks good, just delete the `_id`

2023-09-18 12:46 UTC, SaadiaELF commented on src/Components/forms/index.js
> +      teamData.push({ _id: '65035350fdbf584dc37a3383', name: 'I am not sure' })
You don't need to add the `_id` since it's not and entry on the db , normally the ids are created automatically by mongodb.
```suggestion
      teamData.push({ name: 'I am not sure' })
```

2023-09-18 16:16 UTC, khmdagal commented on src/Components/forms/index.js
> +      teamData.push({ _id: '65035350fdbf584dc37a3383', name: 'I am not sure' })
Done. Removed the id.

2023-09-19 10:13 UTC, SaadiaELF approved these changes
LGFM.

2023-09-19 11:20 UTC, H-BAHDON approved these changes
i can see the option "i am not sure" and can make a request, LGTM

2023-09-20 11:58 UTC, kavitappatil approved these changes
I can see the option -  "I am not sure". LGTM

2023-09-20 18:32 UTC, CanaryWharf approved these changes
Option changed. Code looks okay.

2023-09-21 08:59 UTC, merged

2023-09-21 17:56 UTC, KhesiweDube reviewed
Tested in qa filled in the Volunteer form as "New" It is working as [expected](https://docs.google.com/spreadsheets/d/1I2HC75gY-l5TqIXbzo-VfKzanSVD-gufedGZwkHEHKQ/edit?usp=sharing), The "I'm not sure"  is visible on the form and the teams are in alphabetic order.
When i'm on dashboard the team shows "Select team"  i cannot select "I am not sure" is team not visible on the dashboard.

![765Test1](https://github.com/CodeYourFuture/cyf-forms/assets/101154626/6c3427eb-d3ef-405a-8ef3-f6ff32a3abe8)

![765Test2](https://github.com/CodeYourFuture/cyf-forms/assets/101154626/5a142a23-0fc2-4d15-91d9-2b95df6acda0)

![Screenshot from 2023-09-21 18-17-23](https://github.com/CodeYourFuture/cyf-forms/assets/101154626/370e1805-20ec-4a2d-b014-42696ab58b88)

![Screenshot from 2023-09-21 18-13-02](https://github.com/CodeYourFuture/cyf-forms/assets/101154626/fddd0e31-9060-47d9-a03c-2dcb018f8e01)

2023-09-22 14:10 UTC, AliNurisiahsiahi commented
LGTM.
I [tested](https://docs.google.com/spreadsheets/d/1oMjdAJ3Ghw5JHd1LShx24dRjnFjSB9pvXg2yarJTg8A/edit#gid=1569383378), registered as a new volunteer and filled out the form, The "I'm not sure" is visible on the form, the teams are in alphabetic order and "I am not sure" was at the bottom.
on the dashboard the team shows "Select team" and "I am not sure" are not visible on the dashboard and the user can not select the option "Select team" on the team, the user can select a different option( Career mentor, Education,...) on the team. 

<img width="976" alt="Screenshot 2023-09-22 at 13 46 42" src="https://github.com/CodeYourFuture/cyf-forms/assets/89853649/a84c033a-a37f-4a82-b6dd-be8b1af9cf0a">
<img width="1272" alt="Screenshot 2023-09-22 at 13 53 51" src="https://github.com/CodeYourFuture/cyf-forms/assets/89853649/aa67c1af-8198-4ae6-92df-636c0293fcce">
<img width="1272" alt="Screenshot 2023-09-22 at 13 54 21" src="https://github.com/CodeYourFuture/cyf-forms/assets/89853649/beb72d5d-9700-4195-a19b-73790fc15a1d">