Feature/697-move-employer-names-to-backend-code[QA]
CodeYourFuture/cyf-forms pull request #154
Opened 2024-02-16 21:41 UTC by khmdagal

This is a:

- [x] ✨ **New feature** - new behaviour has been implemented
- [ ] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ✅ **Test backfill** - tests for existing behaviour were added but the behaviour itself hasn't changed
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

### Description

**Purpose** 

The purpose of this PR is that the employers' names list should come from the back-end code. A new volunteer should be able to see all the employers' names on the volunteer's form and be able to select if their employer's name is on the list.

**How to check** 

- Visit this branch: feature/697-move-employer-names-to-backend-code-reduced-scope.
- Run cyf-api repo.
- Run your cyf-forms repo, when the form loads you should be able to see all the employers' names sorted alphabetically.

### Links

1. issue: CodeYourFuture/tech-team#697.

2. Implementing current required changes

- cyf-api: https://github.com/CodeYourFuture/cyf-api/pull/637

3. FYI: Reverting all changes merged to the QA branch

- cyf-form:https://github.com/CodeYourFuture/cyf-forms/pull/153
- cyf-api: https://github.com/CodeYourFuture/cyf-api/pull/635

### Author checklist

- [x] I have written a title that reflects the relevant ticket
- [x] I have written a description that says what the PR does and how to validate it
- [x] I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [x] I have added a link to this PR to the ticket
- [x] I have made the PR to `qa` from a branch named **feature/697-move-employer-names-to-backend-code-reduced-scope**
- [x] I have completed the manual tests [described here](https://github.com/CodeYourFuture/tech-team/wiki/3.-How-we-work#manual-test-procedures)
- [x] I have requested reviewers here and in my team chat channel

- [x] I have spoken with my PM or TL about any parts of this task that may have become out-of-scope, or any additional improvements that I now realise may benefit my project
- [x] I have added tests, or new tests were not required
- [ ] I have updated any documentation (e.g. diagrams, schemas), or documentation updates were not required

2024-03-05 18:02 UTC, CanaryWharf requested changes

2024-03-05 18:02 UTC, CanaryWharf commented on src/Components/forms/index.js
> +      console.log(employersData)
We should avoid leaving console logs in the code unless needed

2024-03-05 18:02 UTC, CanaryWharf commented on yarn.lock
> +  version "1.2.4"
Is there a reason this was updated?

2024-03-05 22:01 UTC, khmdagal commented on src/Components/forms/index.js
> +      console.log(err)
Done

2024-03-05 22:01 UTC, khmdagal commented on src/Components/forms/index.js
> +      console.log(employersData)
Removed

2024-03-05 22:10 UTC, khmdagal commented on yarn.lock
> +  version "1.2.4"
This was not part of the code that I touched and my commits.

2024-03-06 10:14 UTC, textbook commented on src/Components/forms/index.js
> +      employersData.sort((a, b) => a.name.localeCompare(b.name))
Continuing from [here ](https://github.com/CodeYourFuture/cyf-api/pull/637#discussion_r1514188409)it seems you _did know_ you were changing the API interface, but didn't update the docs accordingly. This also **does not** match the fixture used in the e2e tests. Again, get some tests failing to tell you there's a problem.

2024-03-11 22:09 UTC, khmdagal commented on src/Components/forms/index.js
> +      employersData.sort((a, b) => a.name.localeCompare(b.name))
updated the test, so it fails when something wrong happens in the implementation

2024-03-13 22:57 UTC, textbook requested changes
Changes needed on this _and CodeYourFuture/cyf-api#637_ to keep the API consistent.

2024-03-13 22:57 UTC, textbook commented on e2e/integration/journey.test.js
> +  })
:x: It doesn't make sense to test the response here - this is just the fixture you set up on line 11. We test `@createVolunteer` because that's the request the app makes based on the data the user has entered.

```suggestion
```

2024-03-13 22:57 UTC, textbook commented on e2e/integration/journey.test.js
> +    'Capgemini{enter}'
:x: This is what is hiding all of your problems. The employer list is **not** populated, which is why without making this change it fails:
```
[e2e]   1) requires employee selection:
[e2e] 
[e2e]       AssertionError: expected { Object (firstName, lastName, ...) } to have property 'employer' of 'Capgemini', but got 'Cap'
[e2e]       + expected - actual
[e2e] 
[e2e]       -'Cap'
[e2e]       +'Capgemini'
```
With no items in the list the employer can't be auto-completed, so it's submitted as a _new_ employer. 

:question: Maybe we should explicitly check that the corresponding message (_"This employer will be added to our list. Make sure you typed it correctly."_) isn't shown at this point?

```suggestion
    'Cap{enter}'
```

2024-03-13 22:57 UTC, textbook commented on e2e/integration/journey.test.js
> +  }).as('getEmployers')
:bulb: If you don't assert on it you don't need the alias either.
```suggestion
  })
```

2024-03-13 22:57 UTC, textbook commented on e2e/fixtures/employers.json
> +}
:heavy_check_mark: I think this is the right API response, but this is **not** consistently used throughout this and CodeYourFuture/cyf-api#637. It is what's in the API docs (although the `Employer` schema is missing entirely) but isn't in either of the actual implementations.

2024-03-15 21:02 UTC, khmdagal commented on e2e/integration/journey.test.js
> +  })
Removed this change

2024-03-15 21:05 UTC, khmdagal commented on e2e/integration/journey.test.js
> +    'Capgemini{enter}'
I put 'Cap{enter}' back and the tests are passing. But this message ("This employer will be added to our list. Make sure you typed it correctly.") shows whether the employer exists or is newly typed.

2024-03-15 21:06 UTC, khmdagal commented on e2e/integration/journey.test.js
> +  }).as('getEmployers')
Removed this alias

2024-03-15 21:07 UTC, khmdagal commented on e2e/fixtures/employers.json
> +}
Updated the response sent and the way it accessed in the front-end and the docs.

2024-03-15 21:51 UTC, textbook commented on src/Components/forms/index.js
> +      const employersData = response.data.employers
Yes, this is the correction I was looking for 👍

2024-03-21 15:25 UTC, textbook commented on e2e/integration/journey.test.js
> +    'Capgemini{enter}'
That message _isn't_ shown if the employer already exists - the fact that it _was_ being shown is what gave away that `Capgemini` was being entered as a manual addition **not** actually being looked up from the employers data (which wasn't loading correctly due to the response shape mismatches). But it's not critical to add this assertion.

2024-04-02 14:30 UTC, esma-g commented
> Changes needed on this _and [CodeYourFuture/cyf-api#637](https://github.com/CodeYourFuture/cyf-api/pull/637)_ to keep the API consistent.

@khmdagal have you responded to this change request?

2024-04-02 14:30 UTC, esma-g commented
@CanaryWharf could you please confirm that your change requests have been fulfilled?

2024-04-03 08:56 UTC, khmdagal commented
> > Changes needed on this _and [CodeYourFuture/cyf-api#637](https://github.com/CodeYourFuture/cyf-api/pull/637)_ to keep the API consistent.
> 
> @khmdagal have you responded to this change request?

@esma-g Yes I have made all the requested changes.

2024-04-03 09:02 UTC, esma-g commented
@textbook could you accept the changes if you're happy with them?

2024-04-04 19:28 UTC, merged