fixTestPass
CodeYourFuture/cyf-forms pull request #76
Opened 2020-10-19 20:14 UTC by AlexandruBudaca

2020-10-19 20:25 UTC, textbook requested changes
You've solved the core problem, good job! A few minor tweaks required before merging.

2020-10-19 20:25 UTC, textbook commented on package.json
> +    "e2e:dev": "concurrently -k -n \"app,mock,e2e\" \"npm start\" \"npm run e2e:mock\" \"cypress open\"",
These projects use Yarn not NPM, and you definitely don't want a mix between different scripts. See https://github.com/CodeYourFuture/tech-team/wiki/Setting-up-development-environment for information about the local setup.

2020-10-19 20:25 UTC, textbook commented on e2e/integration/journey.test.js
> +  hearAboutCYF: 'Social media',
This doesn't seem to match the data below - the entries are false, but we expect true in the API call. If you're going to have a boolean value here, the box should be ticked only if it's true.

2020-10-19 20:28 UTC, AlexandruBudaca commented on package.json
> +    "e2e:dev": "concurrently -k -n \"app,mock,e2e\" \"npm start\" \"npm run e2e:mock\" \"cypress open\"",
Oh yes. I will install yarn :)

2020-10-19 21:20 UTC, AlexandruBudaca commented on e2e/integration/journey.test.js
> +  hearAboutCYF: 'Social media',
I think i don't need them because there is a condition in handleSubmit and if they are not true they can't submit. Or if we need to test it I need them true because there are mandatory fields and if you check them they became true.

2020-10-19 21:31 UTC, AlexandruBudaca commented on e2e/integration/journey.test.js
> +  hearAboutCYF: 'Social media',
I will use .check() in the command.js for them and I need to be boolean because they are mandatory fieldsan it has to be true.

2020-10-20 08:28 UTC, textbook approved these changes
Looks good, thanks

2020-11-29 17:13 UTC, banirezaie approved these changes
nice changes, thank you

2020-12-01 02:04 UTC, 279Roxana approved these changes
looks ok 👍

2020-12-03 12:34 UTC, Hamidreza-Fakharzadeh approved these changes

2020-12-03 12:35 UTC, Hamidreza-Fakharzadeh commented
nice job

2020-12-19 14:47 UTC, merged