Create pull request template
CodeYourFuture/cyf-forms pull request #94
Opened 2022-09-28 21:14 UTC by Bondcoder

2022-10-11 16:48 UTC, Bondcoder commented
There wasn't a template for this repo.

2022-10-11 17:32 UTC, textbook requested changes
I just tried out the template on #99, looks good. Two minor things to review.

2022-10-11 17:32 UTC, textbook commented on .github/pull_request_template.md
> +- [ ] I have completed the manual tests [described here](https://github.com/CodeYourFuture/tech-team/wiki/Manual-Test-Procedures)
This link is broken and I can't see that page in the wiki - @kfklein15 you've moved some things around, do you know where it got to?

2022-10-11 17:32 UTC, textbook commented on .github/pull_request_template.md
> +- [ ] I have made the PR to `staging` from a branch named `<category>/<name>`, e.g. `feature/edit-spaceships` or `bugfix/restore-oxygen`
This is outdated, we should mention `qa` here too

2023-03-07 23:26 UTC, SaadiaELF commented on .github/pull_request_template.md
> +- [ ] I have completed the manual tests [described here](https://github.com/CodeYourFuture/tech-team/wiki/Manual-Test-Procedures)
@kfklein15 , I couldn't find a link to `manual tests` in Wiki page

2023-03-07 23:33 UTC, textbook commented on .github/pull_request_template.md
> +- [ ] I have completed the manual tests [described here](https://github.com/CodeYourFuture/tech-team/wiki/Manual-Test-Procedures)
Seems to have moved to https://github.com/CodeYourFuture/tech-team/wiki/3.-How-we-work#manual-test-procedures

2023-03-08 00:21 UTC, SaadiaELF approved these changes

2023-03-08 11:22 UTC, kfklein15 approved these changes
LGTM

2023-03-08 11:29 UTC, textbook approved these changes

2023-03-08 12:07 UTC, merged